CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;
DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS(
   -- PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
   PRODUCT_ID INT PRIMARY KEY ,
   PRODUCT_NAME TEXT,
   PRICE INT
) ENGINE = InnoDB;
DESCRIBE PRODUCTS;
SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS;
INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES(100, 'Man''s Search for Meaning', 500);
INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES(101, 'Awaken the Giant Within ', 505);
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE FROM PRODUCTS;