SELECT * FROM EMPLOYEE;

DROP TABLE LEAVE_DETAILS;
CREATE TABLE LEAVE_DETAILS(
   LEAVE_ID INT PRIMARY KEY,
   EMP_ID INT NOT NULL,
   REASON TEXT
);

INSERT INTO LEAVE_DETAILS (LEAVE_ID, EMP_ID,REASON) VALUES (100,200,'SIMPLY, I WANT TO ENJOY MY LIFE!');

SELECT * FROM LEAVE_DETAILS;